[server]
port = 8501
enableCORS = false
enableXsrfProtection = false

[theme]
base = "light"
primaryColor = "#9E2A2B"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"
font = "sans serif"